_target_: pytorch_lightning.Trainer

limit_train_batches: 0.15
limit_val_batches: 0.15
limit_test_batches: 1.0
num_sanity_val_steps: 0
max_epochs: null
min_epochs: null

log_every_n_steps: 200

gradient_clip_val: 5
track_grad_norm: 2
gpus: -1
precision: 16
benchmark: False
deterministic: False
sync_batchnorm: False
detect_anomaly: False
accumulate_grad_batches: 1
resume_from_checkpoint: null
enable_progress_bar: True
