_target_: data_modules.data_h5_womd.DataH5womd

data_dir: /cluster/home/zhejzhan/scratch/h5_womd_sim_agent
filename_train: training
filename_val: validation
filename_test: testing
n_agent: 64

batch_size: 4
num_workers: 4
